PresentationLayer/Controllers/GameController.cs
using BusinessLayer;
using DataLayer.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PresentationLayer.Models;
using System;
using System.Collections.Generic;

namespace PresentationLayer.Views.Game
{
    public class GameController : Controller
    {
        public GameService GameService { get; set; }
        public SpotService SpotService { get; set; }
        public RewardService RewardService { get; set; }
        public IntersectionGameSpotService IntersectionGameSpotService { get; set; }
        public IntersectionGameRewardService IntersectionGameRewardService { get; set; }
        public GameController(GameService gameService, SpotService spotService, RewardService rewardService, IntersectionGameSpotService intersectionGameSpotService, IntersectionGameRewardService intersectionGameRewardService)
        {
            GameService = gameService;
            SpotService = spotService;
            RewardService = rewardService;
            IntersectionGameSpotService = intersectionGameSpotService;
            IntersectionGameRewardService = intersectionGameRewardService;
        }
        public IActionResult Index()
        {
            List<GameModel> allGames = GameService.GetAllGames();
            return View(allGames);
        }

        public IActionResult Edit(Guid Id)
        {
            EditGameViewModel EditGameViewModel = new EditGameViewModel
            {
                Spots = SpotService.GetAllSpots(),
                Rewards = RewardService.GetAllRewards(),
                IntersectionGameSpots = IntersectionGameSpotService.GetAllIntersections(),
                IntersectionGameRewards = IntersectionGameRewardService.GetAllIntersections(),
                GameModel = GameService.GetGameFromGameId(Id)
            };
            return View(EditGameViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(AddGameViewModel addGameViewModel, IFormCollection form, Guid Id)
        {
            GameService.DeleteGame(Id);
            AddGame(addGameViewModel, form);
            return RedirectToAction(nameof(Index));
        }


        public IActionResult Delete(Guid Id)
        {
            GameModel gameToBeDeleted = GameService.GetGameFromGameId(Id);
            return View(gameToBeDeleted);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(Guid Id)
        {
            GameModel gameToBeDeleted = GameService.GetGameFromGameId(Id);
            GameService.DeleteGame(Id);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult AddGame()
        {
            AddGameViewModel addGameViewModel = new AddGameViewModel
            {
                Spots = SpotService.GetAllSpots(),
                Rewards = RewardService.GetAllRewards(),
            };
            return View(addGameViewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddGame(AddGameViewModel addGameViewModel, IFormCollection form)
        {
            GameModel gameModel = addGameViewModel.GameModel;
            gameModel.Id = Guid.NewGuid();
            GameService.AddGame(gameModel);
            LinkGameToSpots(form.Keys, gameModel);
            LinkGameToRewards(form.Keys, gameModel);

            return RedirectToAction(nameof(Index));
        }
        private void LinkGameToSpots(ICollection<string> formKeys, GameModel game)
        {
            List<Spot> allSpots = SpotService.GetAllSpots();
            foreach (string key in formKeys)
            {
                foreach (Spot spot in allSpots)
                {
                    if (spot.Id.ToString() == key)
                    {
                        IntersectionGameSpot intersectionGameSpot = new IntersectionGameSpot
                        {
                            GameId = game.Id,
                            SpotId = spot.Id
                        };
                        IntersectionGameSpotService.AddIntersection(intersectionGameSpot);
                    }
                }
            }
        }
        private void LinkGameToRewards(ICollection<string> formKeys, GameModel game)
        {
            List<Reward> allRewards = RewardService.GetAllRewards();
            foreach (string key in formKeys)
            {
                foreach (Reward reward in allRewards)
                {
                    if (reward.Id.ToString() == key)
                    {
                        IntersectionGameReward intersectionGameReward = new IntersectionGameReward
                        {
                            GameId = game.Id,
                            RewardId = reward.Id
                        };
                        IntersectionGameRewardService.AddIntersection(intersectionGameReward);
                    }
                }
            }
        }

    }
}

PresentationLayer/Controllers/RewardController.cs
using BusinessLayer;
using DataLayer.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;

namespace PresentationLayer.Views.Game
{
    public class RewardController : Controller
    {
        public RewardService RewardService { get; set; }
        public RewardController(RewardService rewardService)
        {
            RewardService = rewardService;
        }
        public IActionResult Index()
        {
            List<Reward> allRewards = RewardService.GetAllRewards();
            return View(allRewards);
        }


        public IActionResult AddReward()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddReward(Reward reward)
        {
            RewardService.AddReward(reward);
            return RedirectToAction(nameof(Index));
        }


        public IActionResult Edit(Guid Id)
        {
            Reward RewardToBeEdited = RewardService.GetRewardFromId(Id);
            return View(RewardToBeEdited);
        }

        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public IActionResult EditConfirmed(Reward newReward)
        {
            RewardService.DeleteReward(newReward.Id);
            AddReward(newReward);
            return RedirectToAction(nameof(Index));
        }


        public IActionResult Delete(Guid Id)
        {
            Reward RewardToBeDeleted = RewardService.GetRewardFromId(Id);
            return View(RewardToBeDeleted);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(Guid Id)
        {
            Reward RewardToBeDeleted = RewardService.GetRewardFromId(Id);
            RewardService.DeleteReward(Id);
            return RedirectToAction(nameof(Index));
        }



    }
}

PresentationLayer/Controllers/SpotController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BusinessLayer;
using DataLayer.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PresentationLayer.Models;

namespace PresentationLayer.Views.Game
{
    public class SpotController : Controller
    {
        public SpotService SpotService { get; set; }
        public SpotController(SpotService spotService)
        {
            SpotService = spotService;
        }
        public IActionResult Index()
        {
            List<Spot> allSpots = SpotService.GetAllSpots();
            return View(allSpots);
        }


        public IActionResult AddSpot()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddSpot(Spot spot)
        {
            SpotService.AddSpot(spot);
            return RedirectToAction(nameof(Index));
        }


        public IActionResult Edit(Guid Id)
        {
            Spot spotToBeEdited = SpotService.GetSpotFromId(Id);
            return View(spotToBeEdited);
        }

        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public IActionResult EditConfirmed(Spot newSpot)
        {
            SpotService.DeleteSpot(newSpot.Id);
            AddSpot(newSpot);
            return RedirectToAction(nameof(Index));
        }


        public IActionResult Delete(Guid Id)
        {
            Spot spotToBeDeleted = SpotService.GetSpotFromId(Id);
            return View(spotToBeDeleted);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(Guid Id)
        {
            Spot spotToBeDeleted = SpotService.GetSpotFromId(Id);
            SpotService.DeleteSpot(Id);
            return RedirectToAction(nameof(Index));
        }



    }
}

PresentationLayer/Views/Shared/_GameLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PresentationLayer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="row">
        <div style="width:150px">
            <div id="sidebar-wrapper">
                <ul class="sidebar-nav flex-grow-1" style="list-style: none;">
                    <li class="nav-item">
                        <a style="background-color:lightgray" class="nav-link text-dark" asp-area="" asp-controller="Game" asp-action="Index">Games</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Spot" asp-action="Index">Spots</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Reward" asp-action="Index">Rewards</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="col-lg-10">
            <main role="main">
                @RenderBody()
            </main>
        </div>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - PresentationLayer - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

<script>
    let current_url = document.location;
    document.querySelectorAll(".navbar .btn").forEach(function (e) {
        if (e.href == current_url) {
            e.classList += " current";
        }
    });
</script>

PresentationLayer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PresentationLayer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="row">
        <div style="width:150px">
            <div id="sidebar-wrapper">
            <ul class="sidebar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Game" asp-action="Index">Games</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Spot" asp-action="Index">Spots</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Reward" asp-action="Index">Rewards</a>
                </li>
            </ul>
        </div>
        </div>
        <div class="col-lg-10">
            <main role="main">
                @RenderBody()
            </main>
        </div>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - PresentationLayer - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

<script>
    let current_url = document.location;
    document.querySelectorAll(".navbar .btn").forEach(function (e) {
        if (e.href == current_url) {
            e.classList += " current";
        }
    });
</script>

PresentationLayer/Views/Shared/_RewardLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PresentationLayer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="row">
        <div style="width:150px">
            <div id="sidebar-wrapper">
                <ul class="sidebar-nav flex-grow-1" style="list-style: none;">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Game" asp-action="Index">Games</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Spot" asp-action="Index">Spots</a>
                    </li>
                    <li class="nav-item">
                        <a  style="background-color:lightgray" class="nav-link text-dark" asp-area="" asp-controller="Reward" asp-action="Index">Rewards</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="col-lg-10">
            <main role="main">
                @RenderBody()
            </main>
        </div>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - PresentationLayer - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

<script>
    let current_url = document.location;
    document.querySelectorAll(".navbar .btn").forEach(function (e) {
        if (e.href == current_url) {
            e.classList += " current";
        }
    });
</script>

PresentationLayer/Views/Shared/_SpotLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PresentationLayer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="row">
        <div style="width:150px">
            <div id="sidebar-wrapper">
                <ul class="sidebar-nav flex-grow-1" style="list-style: none;">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Game" asp-action="Index">Games</a>
                    </li>
                    <li class="nav-item">
                        <a style="background-color:lightgray" class="nav-link text-dark" asp-area="" asp-controller="Spot" asp-action="Index">Spots</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Reward" asp-action="Index">Rewards</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="col-lg-10">
            <main role="main">
                @RenderBody()
            </main>
        </div>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - PresentationLayer - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

<script>
    let current_url = document.location;
    document.querySelectorAll(".navbar .btn").forEach(function (e) {
        if (e.href == current_url) {
            e.classList += " current";
        }
    });
</script>